apiVersion: v1
data:
  .dockerconfigjson: $DOCKER_CONFIG_JSON
kind: Secret
metadata:
  name: docker
  namespace: $NAMESPACE
type: kubernetes.io/dockerconfigjson
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bridg-experience-dc
  namespace: $NAMESPACE
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bridg-experience-dc
    spec:
      containers:
        - image: docker.io/vasviews/bridg:$CS_VERSION
          name: bridg-experience-dc
          resources:
            limits:
              cpu: "500m"
              memory: "2.5G"
          env:
            - name: AWS_ACCESS_KEY_ID
              value: $DU_AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              value: $DU_AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: us-gov-west-1
            - name: AWS_BUCKET_NAME
              value: $DU_AWS_BUCKET_NAME
            - name: AWS_CONFIG_FOLDER
              value: $DU_S3_FOLDER/bridg-experience
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
      imagePullSecrets:
        - name: docker
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bridg-experience
  namespace: $NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bridg-experience-dc
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: "375m"
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: "1788Mi"
