apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $CS_VERSION
    deployment-test-status: UNTESTED
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: carma-search-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api/carma/(.*)
            backend:
              serviceName: carma-search
              servicePort: 80
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: carma-resource-quota
  namespace: $DU_NAMESPACE
spec:
  hard:
    limits.cpu: "1500m"
    limits.memory: "7.5G"
