---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  namespace: hello
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /hello/?(.*)
            backend:
              serviceName: hello
              servicePort: 80
