---
apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
  labels:
    deployment-id: $K8S_DEPLOYMENT_ID
    deployment-unit: $PRODUCT
    deployment-unit-artifact: $DU_ARTIFACT
    deployment-unit-version: $DU_VERSION
    deployment-date: $BUILD_DATE
    deployment-s3-bucket: $DU_AWS_BUCKET_NAME
    deployment-s3-folder: $DU_S3_FOLDER
    deployment-app-version: $DQ_VERSION
    deployment-test-status: UNTESTED
#---
#apiVersion: v1
#kind: ResourceQuota
#metadata:
#  name: data-query-resource-quota
#  namespace: $DU_NAMESPACE
#spec:
#  hard:
#    limits.cpu: "7800m"
#    limits.memory: "15G"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data-query-dstu2-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /dstu2/$1
spec:
  rules:
    - http:
        paths:
          - path: /fhir/v0/dstu2/(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data-query-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /dstu2/$1
spec:
  rules:
    - http:
        paths:
          - path: /fhir/v0/argonaut/data-query/(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fhir-version-agnostic-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2$3
spec:
  rules:
    - http:
        paths:
          - path: /fhir/v0/(dstu2|argonaut/data-query)/(.well-known|token)(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internal-data-query-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /data-query/(.*)
            backend:
              serviceName: health-apis-kong
              servicePort: 8082
