apiVersion: v1
kind: Namespace
metadata:
  name: $DU_NAMESPACE
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: salesforce-ingress
  namespace: $DU_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /(api/)?(patsr|sfdc|vimt)(.*)
            backend:
              serviceName: salesforce
              servicePort: 8091
