apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: views-squares-ingress
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /(api/)?squares(.*)
            backend:
              serviceName: squares-experience
              servicePort: 7001